const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json',...headers}});
const id=(prefix)=>prefix+'-'+Math.random().toString(36).slice(2,7).toUpperCase();
async function hash(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sendEmail(env,to,subject,text){if(!env.RESEND_API_KEY||!env.MAIL_FROM)return;await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:env.MAIL_FROM,to,subject,text})})}
async function auth(req,env){const c=req.headers.get('Cookie')||'';const m=c.match(/rk_session=([^;]+)/);if(!m)return null;const h=await hash(m[1]);const row=await env.DB.prepare('SELECT a.* FROM sessions s JOIN authors a ON a.id=s.author_id WHERE s.token_hash=? AND s.expires_at>?').bind(h,new Date().toISOString()).first();return row||null}
export async function onRequest(context){const {request,env}=context;const u=new URL(request.url);const p=u.pathname;try{
if(request.method==='POST'&&p==='/api/register'){const d=await request.json();if(!d.participant_name||!d.participant_email||!d.participant_phone||!Array.isArray(d.events)||!d.events.length)return json({error:'Please complete all required fields.'},400);const rid=id('APS');const now=new Date().toISOString();await env.DB.prepare('INSERT INTO registrations(id,created_at,participation_type,team_name,participant_name,participant_email,participant_phone,school,city,members_json,events_json,message) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(rid,now,d.participation_type||'Solo',d.team_name||'',d.participant_name,d.participant_email,d.participant_phone,d.school||'',d.city||'',JSON.stringify(d.members||[]),JSON.stringify(d.events),d.message||'').run();await Promise.all([sendEmail(env,d.participant_email,'RoboKriti registration received',`Your registration ID is ${rid}. Status: Pending Approval.`),env.AUTHOR_EMAIL?sendEmail(env,env.AUTHOR_EMAIL,`New RoboKriti registration ${rid}`,`${d.participant_name} registered for ${d.events.join(', ')}.`):Promise.resolve()]);return json({id:rid},201)}
if(request.method==='POST'&&p==='/api/help'){const d=await request.json();if(!d.name||!d.email||!d.subject||!d.message)return json({error:'Please complete the required fields.'},400);const tid=id('APS');const now=new Date().toISOString();await env.DB.prepare('INSERT INTO help_tickets(id,created_at,name,email,phone,category,subject,message) VALUES(?,?,?,?,?,?,?,?)').bind(tid,now,d.name,d.email,d.phone||'',d.category||'Other',d.subject,d.message).run();await Promise.all([sendEmail(env,d.email,'RoboKriti help request received',`Your help ticket is ${tid}. Our team will review it.`),env.AUTHOR_EMAIL?sendEmail(env,env.AUTHOR_EMAIL,`New RoboKriti help ticket ${tid}`,`${d.subject}\n${d.message}`):Promise.resolve()]);return json({id:tid},201)}
if(request.method==='GET'&&p.startsWith('/api/help/')){const row=await env.DB.prepare('SELECT id,status,reply FROM help_tickets WHERE id=?').bind(p.split('/').pop()).first();return row?json(row):json({error:'Ticket not found.'},404)}
if(request.method==='POST'&&p==='/api/auth/login'){const d=await request.json();const a=await env.DB.prepare('SELECT * FROM authors WHERE email=?').bind(d.email).first();if(!a||await hash(d.password)!==a.password_hash)return json({error:'Invalid credentials.'},401);const token=crypto.randomUUID()+crypto.randomUUID();const th=await hash(token);const exp=new Date(Date.now()+8*60*60*1000).toISOString();await env.DB.prepare('INSERT INTO sessions(token_hash,author_id,expires_at) VALUES(?,?,?)').bind(th,a.id,exp).run();return json({ok:true},200,{'Set-Cookie':`rk_session=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=28800`})}
if(request.method==='POST'&&p==='/api/auth/logout'){const c=request.headers.get('Cookie')||'';const m=c.match(/rk_session=([^;]+)/);if(m)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hash(m[1])).run();return json({ok:true},200,{'Set-Cookie':'rk_session=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict'})}
if(request.method==='GET'&&p==='/api/author/data'){const a=await auth(request,env);if(!a)return json({error:'Unauthorized'},401);const regs=await env.DB.prepare('SELECT * FROM registrations ORDER BY created_at DESC').all();const tickets=await env.DB.prepare('SELECT * FROM help_tickets ORDER BY created_at DESC').all();return json({registrations:regs.results,tickets:tickets.results})}
return new Response('Not found',{status:404})}catch(e){return json({error:'Server error.'},500)}}
