(() => {
 const role=window.PORTAL_ROLE||sessionStorage.getItem('rkRole'); if(!role){location.href='index.html';return}
 const roleName=document.getElementById('roleName'),roleUpper=document.getElementById('roleUpper'); if(roleName)roleName.textContent=role==='admin'?'Registration':'Helping';if(roleUpper)roleUpper.textContent=role==='admin'?'REGISTRATION':'HELPING';
 const stats=document.getElementById('stats'),wrap=document.getElementById('tableWrap'),title=document.getElementById('panelTitle'); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 function load(){const db=RoboDB.all();role==='admin'?renderRegs(db.registrations):renderTickets(db.tickets)}
 function renderRegs(rows){title.textContent='Registrations';stats.innerHTML=`<div><b>${rows.length}</b><span>Total</span></div><div><b>${rows.filter(x=>x.status==='Pending').length}</b><span>Pending</span></div><div><b>${rows.filter(x=>x.status==='Approved').length}</b><span>Approved</span></div>`;wrap.innerHTML=`<div class="table-scroll"><table><thead><tr><th>ID</th><th>Student / Team</th><th>Events</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.registrationId)}</td><td><b>${esc(x.StudentName)}</b><small>${esc(x.TeamName||'')}</small></td><td>${esc((x.Events||[]).join(', '))}</td><td><select data-id="${esc(x.id)}" class="status"><option ${x.status==='Pending'?'selected':''}>Pending</option><option ${x.status==='Approved'?'selected':''}>Approved</option><option ${x.status==='Rejected'?'selected':''}>Rejected</option></select></td><td><button class="save" data-id="${esc(x.id)}">Save</button> <button class="del" data-id="${esc(x.id)}">Delete</button></td></tr>`).join('')}</tbody></table></div>`;bind('registration')}
 function renderTickets(rows){title.textContent='Help Tickets';stats.innerHTML=`<div><b>${rows.length}</b><span>Total</span></div><div><b>${rows.filter(x=>x.status==='Open').length}</b><span>Open</span></div><div><b>${rows.filter(x=>x.status==='Closed').length}</b><span>Closed</span></div>`;wrap.innerHTML=`<div class="table-scroll"><table><thead><tr><th>Reference</th><th>Requester</th><th>Message</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.referenceId)}</td><td>${esc(x.name||x.email||'')}</td><td>${esc(x.message||x.subject||'')}</td><td><select data-id="${esc(x.id)}" class="status"><option ${x.status==='Open'?'selected':''}>Open</option><option ${x.status==='In Progress'?'selected':''}>In Progress</option><option ${x.status==='Closed'?'selected':''}>Closed</option></select></td><td><button class="save" data-id="${esc(x.id)}">Save</button> <button class="del" data-id="${esc(x.id)}">Delete</button></td></tr>`).join('')}</tbody></table></div>`;bind('ticket')}
 function bind(type){wrap.querySelectorAll('.save').forEach(b=>b.onclick=()=>{const sel=wrap.querySelector(`select[data-id="${CSS.escape(b.dataset.id)}"]`),status=sel.value;RoboDB.update(type,b.dataset.id,type==='ticket'?{status,progress:status==='Closed'?100:status==='In Progress'?50:10,status_note:status==='Closed'?'Resolved.':'Your request is being handled.'}:{status});load()});wrap.querySelectorAll('.del').forEach(b=>b.onclick=()=>{if(confirm('Delete this record?')){RoboDB.remove(type,b.dataset.id);load()}})}
 document.getElementById('refresh')?.addEventListener('click',load);document.getElementById('logout')?.addEventListener('click',()=>{sessionStorage.removeItem('rkRole');location.href='index.html'});load();
})();
