(()=>{
 const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const boot=()=>{if(document.querySelector('.rk-preloader'))return;const el=document.createElement('div');el.className='rk-preloader';el.innerHTML='<div class="rk-loader"><div class="rk-loader-top"><span>ROBOKRITI // SYSTEM</span><span id="rkPct">00%</span></div><div class="rk-loader-bar"><i id="rkBar"></i></div><div class="rk-loader-word">BUILD<span>.</span>CODE<span>.</span>COMPETE<span>.</span></div></div>';document.body.prepend(el);let n=0;const tick=setInterval(()=>{n=Math.min(100,n+Math.floor(Math.random()*18)+8);el.querySelector('#rkBar').style.width=n+'%';el.querySelector('#rkPct').textContent=String(n).padStart(2,'0')+'%';if(n>=100){clearInterval(tick);setTimeout(()=>el.classList.add('done'),180)}},90)};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
 const mark=()=>{document.querySelectorAll('section,.arena-card,.core-card,.contact-card,.operations-grid article,.rule-card,.side-card,.leadership-feature,.journey>div,.final-cta,.mentor-message').forEach((e,i)=>{if(!e.classList.contains('reveal')){e.classList.add('reveal');e.style.transitionDelay=Math.min(i%8*55,385)+'ms'}});if(reduce){document.querySelectorAll('.reveal').forEach(e=>e.classList.add('in-view'));return}const io=new IntersectionObserver(es=>es.forEach(x=>x.isIntersecting&&(x.target.classList.add('in-view'),io.unobserve(x.target))),{threshold:.10,rootMargin:'0px 0px -50px'});document.querySelectorAll('.reveal').forEach(e=>io.observe(e))};
 setTimeout(mark,80);
 // Smooth extensionless navigation. Keep URLs clean and avoid browser showing .html.
 document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a||a.target==='_blank'||a.origin!==location.origin)return;const href=a.getAttribute('href');if(!href||href.startsWith('#')||href.startsWith('mailto:')||href.startsWith('tel:'))return;if(/\.html(?:[?#]|$)/.test(href)){e.preventDefault();const clean=href.replace(/\.html(?=($|[?#]))/,'/');history.pushState({},'',clean);location.reload()}});
 window.addEventListener('pageshow',()=>document.documentElement.classList.add('rk-ready'));
})();
